{% set name = "jupyter_sphinx" %}
{% set version = "0.2.0" %}
{% set sha256 = "4ff879a722e5403779d5f33be99bf9b0d37d8f9fd2a339efa786e0ba9ded744b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<35]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
  run:
    - python
    - sphinx >=0.6
    - ipywidgets >=7.0.0
    - IPython
    - nbconvert >=5.5
    - nbformat

test:
  imports:
    - jupyter_sphinx

about:
  home: https://github.com/jupyter/jupyter-sphinx
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Include Jupyter outputs in Sphinx documentation.'
  dev_url: https://github.com/jupyter/jupyter-sphinx

extra:
  recipe-maintainers:
    - SylvainCorlay
