{% set name = "jupyter_sphinx" %}
{% set version = "0.3.1" %}
{% set sha256 = "c4caf8bbf2be6edfe0319aa76127d17fdbe6927c8189cda2d6ac59c01f38404b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

requirements:
  run:
    - jupyter-sphinx=={{version}}

about:
  home: https://github.com/jupyter/jupyter-sphinx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Include Jupyter outputs in Sphinx documentation.
  dev_url: https://github.com/jupyter/jupyter-sphinx

extra:
  recipe-maintainers:
    - SylvainCorlay
    - akhmerov
    - jbweston
