travis:
  secure:
    BINSTAR_TOKEN: dHZBi5CUGvYi5FEWJ/8B3UyIOC4I+NI9iogLSSEHXvpduxpZS+u4qpaW4gspZPJhNRyu7Pa0LE3Ir6M00lwEmyJrBZqKsWWQ+Q4tKP/HxMpiFL6cgPKpsPViH6MBcOlG/u0iS+7rcmLH2Y3Yi7c5zrQO+gnYkNO9TPIASPgB1PRN4t0V8PPzyt33fLOm2aCEk4b6zm5OpPYG0nUwAldBFaHwI+doZ1K3DYGtPmHG6Hy+4iP6hFcPd1TKuO/CZF7Wh4wHJbUp4eS5Afxy3OQn2KDfnnerz1tXP/Z8fZxBX0+YFMOmZxKIhevU2rQdEo2/I7RHFPnocl/tZ/pIrSyaF6giwPnhHph0VNp8XA+NIHssv1DQhYjC2A5a9683ZO9OQDA5MP9T/iPmXSOIKf7+x2SF8i+aQ/wxjuxX9P5VHDcgeEsxhLAf8/fmGBpoRnKjD80JaxtvVapNnA42K2xjLcVE9VMj2vRB8F2DZ/ilur+6bUb8aeyjFPZUoNUrAJqcLeCusyg6JRphKVetdObER++eY5oZBbpZgT8+xelwvZlSTw/4teG98Po566go3EOWa8cccgklfTAh4rOE09Y8gOlw1Kv2jXZR25iCtsRr+hbHEOP21O8gPflvBrUMxhBedzVdMOmokat6KZjbgRrXfSk07MzC/b5/u2n9e+ZSRVM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
